Hotfix handle exceptions properly
StuartApp/aws-prom-exporter pull request #3
Opened 2021-09-29 10:35 UTC by bvcelari

2021-09-29 10:38 UTC, esanchezm requested changes

2021-09-29 10:38 UTC, esanchezm commented on aws_prom_exporter/modules/auth/vault.py
> +            raise UnknownException from e
Ths `UnknownException` class doesn't exist so this raise will fail with another exception :sweat_smile:

2021-09-29 10:57 UTC, bvcelari commented on aws_prom_exporter/modules/auth/vault.py
> +            raise UnknownException from e
sorry, that should be removed!

2021-09-29 12:54 UTC, esanchezm approved these changes

2021-09-30 07:17 UTC, jordiclariana approved these changes

2022-02-17 14:11 UTC, merged